# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Capstone/UI/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!
import FreshWaterInfo
import GreyWaterInfo
import BlackWaterInfo
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 480)
        MainWindow.setMaximumSize(QtCore.QSize(1250, 850))
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setMinimumSize(QtCore.QSize(720, 480))
        self.centralWidget.setMaximumSize(QtCore.QSize(1250, 850))
        self.centralWidget.setObjectName("centralWidget")
        self.TabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.TabWidget.setGeometry(QtCore.QRect(1, -10, 720, 480))
        self.TabWidget.setMinimumSize(QtCore.QSize(720, 480))
        self.TabWidget.setMaximumSize(QtCore.QSize(1250, 850))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TabWidget.setFont(font)
        self.TabWidget.setAccessibleName("")
        self.TabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.TabWidget.setUsesScrollButtons(True)
        self.TabWidget.setDocumentMode(False)
        self.TabWidget.setTabsClosable(False)
        self.TabWidget.setMovable(False)
        self.TabWidget.setTabBarAutoHide(False)
        self.TabWidget.setObjectName("TabWidget")
        self.SensorInformation = QtWidgets.QWidget()
        self.SensorInformation.setObjectName("SensorInformation")
        self.FreshWaterProgressBar = QtWidgets.QProgressBar(self.SensorInformation)
        self.FreshWaterProgressBar.setGeometry(QtCore.QRect(70, 150, 270, 70))
        self.FreshWaterProgressBar.setMinimumSize(QtCore.QSize(270, 70))
        freshwater = FreshWaterInfo.getFreshWater()
        self.FreshWaterProgressBar.setProperty("value", 50)
        self.FreshWaterProgressBar.setObjectName("FreshWaterProgressBar")
        self.BlackWaterProgressBar = QtWidgets.QProgressBar(self.SensorInformation)
        self.BlackWaterProgressBar.setGeometry(QtCore.QRect(70, 300, 270, 70))
        self.BlackWaterProgressBar.setMinimumSize(QtCore.QSize(270, 70))
        self.BlackWaterProgressBar.setProperty("value", 50)
        self.BlackWaterProgressBar.setObjectName("BlackWaterProgressBar")
        self.GreyWaterProgressBar = QtWidgets.QProgressBar(self.SensorInformation)
        self.GreyWaterProgressBar.setGeometry(QtCore.QRect(380, 150, 270, 70))
        self.GreyWaterProgressBar.setMinimumSize(QtCore.QSize(270, 70))
        self.GreyWaterProgressBar.setProperty("value", 50)
        self.GreyWaterProgressBar.setObjectName("GreyWaterProgressBar")
        self.BatteryProgressBar = QtWidgets.QProgressBar(self.SensorInformation)
        self.BatteryProgressBar.setGeometry(QtCore.QRect(380, 300, 270, 70))
        self.BatteryProgressBar.setMinimumSize(QtCore.QSize(270, 70))
        self.BatteryProgressBar.setProperty("value", 24)
        self.BatteryProgressBar.setObjectName("BatteryProgressBar")
        self.BlackWaterLabel = QtWidgets.QLabel(self.SensorInformation)
        self.BlackWaterLabel.setGeometry(QtCore.QRect(70, 270, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.BlackWaterLabel.setFont(font)
        self.BlackWaterLabel.setObjectName("BlackWaterLabel")
        self.FreshWaterLabel = QtWidgets.QLabel(self.SensorInformation)
        self.FreshWaterLabel.setGeometry(QtCore.QRect(70, 120, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.FreshWaterLabel.setFont(font)
        self.FreshWaterLabel.setObjectName("FreshWaterLabel")
        self.GreyWaterLabel = QtWidgets.QLabel(self.SensorInformation)
        self.GreyWaterLabel.setGeometry(QtCore.QRect(380, 120, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.GreyWaterLabel.setFont(font)
        self.GreyWaterLabel.setObjectName("GreyWaterLabel")
        self.BatteryLabel = QtWidgets.QLabel(self.SensorInformation)
        self.BatteryLabel.setGeometry(QtCore.QRect(380, 270, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.BatteryLabel.setFont(font)
        self.BatteryLabel.setObjectName("BatteryLabel")
        self.TabWidget.addTab(self.SensorInformation, "")
        self.UsageHistory = QtWidgets.QWidget()
        self.UsageHistory.setObjectName("UsageHistory")
        self.FreshWaterUsageLabel = QtWidgets.QLabel(self.UsageHistory)
        self.FreshWaterUsageLabel.setGeometry(QtCore.QRect(110, 80, 101, 31))
        self.FreshWaterUsageLabel.setObjectName("FreshWaterUsageLabel")
        self.GreyWaterUsageLabel = QtWidgets.QLabel(self.UsageHistory)
        self.GreyWaterUsageLabel.setGeometry(QtCore.QRect(390, 80, 101, 31))
        self.GreyWaterUsageLabel.setObjectName("GreyWaterUsageLabel")
        self.BlackWaterUsageLabel = QtWidgets.QLabel(self.UsageHistory)
        self.BlackWaterUsageLabel.setGeometry(QtCore.QRect(110, 250, 101, 31))
        self.BlackWaterUsageLabel.setObjectName("BlackWaterUsageLabel")
        self.BatterUsageLabel = QtWidgets.QLabel(self.UsageHistory)
        self.BatterUsageLabel.setGeometry(QtCore.QRect(390, 250, 101, 31))
        self.BatterUsageLabel.setObjectName("BatterUsageLabel")
        self.TabWidget.addTab(self.UsageHistory, "")
        self.Power = QtWidgets.QWidget()
        self.Power.setObjectName("Power")
        self.appPower = QtWidgets.QPushButton(self.Power)
        self.appPower.setGeometry(QtCore.QRect(120, 170, 140, 140))
        self.appPower.setMinimumSize(QtCore.QSize(140, 140))
        self.appPower.setMaximumSize(QtCore.QSize(140, 140))
        self.appPower.setAutoFillBackground(False)
        self.appPower.setStyleSheet("")
        self.appPower.setText("")
        self.appPower.setObjectName("appPower")
        self.raspPower = QtWidgets.QPushButton(self.Power)
        self.raspPower.setGeometry(QtCore.QRect(420, 170, 200, 200))
        self.raspPower.setMinimumSize(QtCore.QSize(200, 200))
        self.raspPower.setMaximumSize(QtCore.QSize(200, 200))
        self.raspPower.setObjectName("raspPower")
        self.TabWidget.addTab(self.Power, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FreshWaterProgressBar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Adjust to the content of the fresh water tank</p></body></html>"))
        self.BlackWaterLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Black Water</span></p></body></html>"))
        self.FreshWaterLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Fresh Water</span></p></body></html>"))
        self.GreyWaterLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Grey Water</span></p></body></html>"))
        self.BatteryLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Battery</span></p></body></html>"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.SensorInformation), _translate("MainWindow", "SensorInformation"))
        self.TabWidget.setTabToolTip(self.TabWidget.indexOf(self.SensorInformation), _translate("MainWindow", "Click to see status of sensors"))
        self.FreshWaterUsageLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Fresh Water</span></p></body></html>"))
        self.GreyWaterUsageLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Grey Water</span></p></body></html>"))
        self.BlackWaterUsageLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Black Water</span></p></body></html>"))
        self.BatterUsageLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Battery</span></p></body></html>"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.UsageHistory), _translate("MainWindow", "UsageHistory"))
        self.TabWidget.setTabToolTip(self.TabWidget.indexOf(self.UsageHistory), _translate("MainWindow", "Click to see the history of the devices usage through graphs"))
        self.appPower.setStatusTip(_translate("MainWindow", "Click to turn off the Application"))
        self.appPower.setWhatsThis(_translate("MainWindow", "Turns off the application"))
        self.raspPower.setStatusTip(_translate("MainWindow", "Click to turn off the Raspberry Pi"))
        self.raspPower.setWhatsThis(_translate("MainWindow", "Turns off the Raspberry Pi"))
        self.raspPower.setText(_translate("MainWindow", "Turn off Pi"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Power), _translate("MainWindow", "Power"))

import new_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

