# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/eeddey/Desktop/Capstone/UI/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 480)
        MainWindow.setMaximumSize(QtCore.QSize(720, 480))
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralWidget.setMaximumSize(QtCore.QSize(720, 480))
        self.centralWidget.setObjectName("centralWidget")
        self.TabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.TabWidget.setGeometry(QtCore.QRect(1, -10, 720, 480))
        self.TabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.TabWidget.setMaximumSize(QtCore.QSize(720, 850))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TabWidget.setFont(font)
        self.TabWidget.setAccessibleName("")
        self.TabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.TabWidget.setUsesScrollButtons(True)
        self.TabWidget.setDocumentMode(False)
        self.TabWidget.setTabsClosable(False)
        self.TabWidget.setMovable(False)
        self.TabWidget.setTabBarAutoHide(False)
        self.TabWidget.setObjectName("TabWidget")
        self.SensorInformation = QtWidgets.QWidget()
        self.SensorInformation.setObjectName("SensorInformation")
        self.FreshWaterProgressBar = QtWidgets.QProgressBar(self.SensorInformation)
        self.FreshWaterProgressBar.setGeometry(QtCore.QRect(70, 150, 270, 70))
        self.FreshWaterProgressBar.setMinimumSize(QtCore.QSize(270, 70))
        self.FreshWaterProgressBar.setProperty("value", 24)
        self.FreshWaterProgressBar.setObjectName("FreshWaterProgressBar")
        self.BlackWaterProgressBar = QtWidgets.QProgressBar(self.SensorInformation)
        self.BlackWaterProgressBar.setGeometry(QtCore.QRect(70, 300, 270, 70))
        self.BlackWaterProgressBar.setMinimumSize(QtCore.QSize(270, 70))
        self.BlackWaterProgressBar.setProperty("value", 24)
        self.BlackWaterProgressBar.setObjectName("BlackWaterProgressBar")
        self.GreyWaterProgressBar = QtWidgets.QProgressBar(self.SensorInformation)
        self.GreyWaterProgressBar.setGeometry(QtCore.QRect(380, 150, 270, 70))
        self.GreyWaterProgressBar.setMinimumSize(QtCore.QSize(270, 70))
        self.GreyWaterProgressBar.setProperty("value", 24)
        self.GreyWaterProgressBar.setObjectName("GreyWaterProgressBar")
        self.BatteryProgressBar = QtWidgets.QProgressBar(self.SensorInformation)
        self.BatteryProgressBar.setGeometry(QtCore.QRect(380, 300, 270, 70))
        self.BatteryProgressBar.setMinimumSize(QtCore.QSize(270, 70))
        self.BatteryProgressBar.setProperty("value", 24)
        self.BatteryProgressBar.setObjectName("BatteryProgressBar")
        self.BlackWaterLabel = QtWidgets.QLabel(self.SensorInformation)
        self.BlackWaterLabel.setGeometry(QtCore.QRect(70, 270, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.BlackWaterLabel.setFont(font)
        self.BlackWaterLabel.setObjectName("BlackWaterLabel")
        self.FreshWaterLabel = QtWidgets.QLabel(self.SensorInformation)
        self.FreshWaterLabel.setGeometry(QtCore.QRect(70, 120, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.FreshWaterLabel.setFont(font)
        self.FreshWaterLabel.setObjectName("FreshWaterLabel")
        self.GreyWaterLabel = QtWidgets.QLabel(self.SensorInformation)
        self.GreyWaterLabel.setGeometry(QtCore.QRect(380, 120, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.GreyWaterLabel.setFont(font)
        self.GreyWaterLabel.setObjectName("GreyWaterLabel")
        self.BatteryLabel = QtWidgets.QLabel(self.SensorInformation)
        self.BatteryLabel.setGeometry(QtCore.QRect(380, 270, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.BatteryLabel.setFont(font)
        self.BatteryLabel.setObjectName("BatteryLabel")
        self.StatusBackground = QtWidgets.QLabel(self.SensorInformation)
        self.StatusBackground.setGeometry(QtCore.QRect(0, 10, 720, 480))
        self.StatusBackground.setMinimumSize(QtCore.QSize(720, 480))
        self.StatusBackground.setMaximumSize(QtCore.QSize(1250, 850))
        self.StatusBackground.setObjectName("StatusBackground")
        self.StatusBackground.raise_()
        self.FreshWaterProgressBar.raise_()
        self.BlackWaterProgressBar.raise_()
        self.GreyWaterProgressBar.raise_()
        self.BatteryProgressBar.raise_()
        self.BlackWaterLabel.raise_()
        self.FreshWaterLabel.raise_()
        self.GreyWaterLabel.raise_()
        self.BatteryLabel.raise_()
        self.TabWidget.addTab(self.SensorInformation, "")
        self.UsageHistory = QtWidgets.QWidget()
        self.UsageHistory.setObjectName("UsageHistory")
        self.HistoryBackground = QtWidgets.QLabel(self.UsageHistory)
        self.HistoryBackground.setGeometry(QtCore.QRect(0, -20, 720, 480))
        self.HistoryBackground.setMinimumSize(QtCore.QSize(720, 480))
        self.HistoryBackground.setObjectName("HistoryBackground")
        self.CheckGraphs = QtWidgets.QPushButton(self.UsageHistory)
        self.CheckGraphs.setGeometry(QtCore.QRect(310, 390, 87, 29))
        self.CheckGraphs.setObjectName("CheckGraphs")
        self.SensorGraph = MplWidget(self.UsageHistory)
        self.SensorGraph.setGeometry(QtCore.QRect(0, 0, 711, 379))
        self.SensorGraph.setObjectName("SensorGraph")
        self.TabWidget.addTab(self.UsageHistory, "")
        self.Power = QtWidgets.QWidget()
        self.Power.setObjectName("Power")
        self.PowerBackground = QtWidgets.QLabel(self.Power)
        self.PowerBackground.setGeometry(QtCore.QRect(0, 0, 720, 480))
        self.PowerBackground.setMinimumSize(QtCore.QSize(720, 480))
        self.PowerBackground.setObjectName("PowerBackground")
        self.powerApp = QtWidgets.QPushButton(self.Power)
        self.powerApp.setGeometry(QtCore.QRect(100, 120, 195, 205))
        self.powerApp.setMinimumSize(QtCore.QSize(140, 140))
        self.powerApp.setMaximumSize(QtCore.QSize(195, 205))
        self.powerApp.setAutoFillBackground(False)
        self.powerApp.setStyleSheet("background-image: url(:/newPrefix/powerApp.png);")
        self.powerApp.setText("")
        self.powerApp.setObjectName("powerApp")
        self.powerRasberry = QtWidgets.QPushButton(self.Power)
        self.powerRasberry.setGeometry(QtCore.QRect(420, 120, 195, 205))
        self.powerRasberry.setMinimumSize(QtCore.QSize(195, 200))
        self.powerRasberry.setMaximumSize(QtCore.QSize(300, 300))
        self.powerRasberry.setStyleSheet("background-image: url(:/newPrefix/raspberrypi.png);")
        self.powerRasberry.setObjectName("powerRasberry")
        self.TabWidget.addTab(self.Power, "")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 720, 480))
        self.label.setMinimumSize(QtCore.QSize(720, 480))
        self.label.setMaximumSize(QtCore.QSize(1250, 850))
        self.label.setLineWidth(0)
        self.label.setObjectName("label")
        self.label.raise_()
        self.TabWidget.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.powerApp, self.TabWidget)
        MainWindow.setTabOrder(self.TabWidget, self.powerRasberry)
        MainWindow.setTabOrder(self.powerRasberry, self.CheckGraphs)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FreshWaterProgressBar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Adjust to the content of the fresh water tank</p></body></html>"))
        self.BlackWaterLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Black Water</span></p></body></html>"))
        self.FreshWaterLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Fresh Water</span></p></body></html>"))
        self.GreyWaterLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Grey Water</span></p></body></html>"))
        self.BatteryLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Battery</span></p></body></html>"))
        self.StatusBackground.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/background.jpg\"/></p></body></html>"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.SensorInformation), _translate("MainWindow", "SensorInformation"))
        self.TabWidget.setTabToolTip(self.TabWidget.indexOf(self.SensorInformation), _translate("MainWindow", "Click to see status of sensors"))
        self.HistoryBackground.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/background.jpg\"/></p></body></html>"))
        self.CheckGraphs.setText(_translate("MainWindow", "Refresh"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.UsageHistory), _translate("MainWindow", "UsageHistory"))
        self.TabWidget.setTabToolTip(self.TabWidget.indexOf(self.UsageHistory), _translate("MainWindow", "Click to see the history of the devices usage through graphs"))
        self.PowerBackground.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/background.jpg\"/></p></body></html>"))
        self.powerApp.setStatusTip(_translate("MainWindow", "Click to turn off the Application"))
        self.powerApp.setWhatsThis(_translate("MainWindow", "Turns off the application"))
        self.powerRasberry.setStatusTip(_translate("MainWindow", "Click to turn off the Raspberry Pi"))
        self.powerRasberry.setWhatsThis(_translate("MainWindow", "Turns off the Raspberry Pi"))
        self.powerRasberry.setText(_translate("MainWindow", "Turn off Pi"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Power), _translate("MainWindow", "Power"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/background.jpg\"/></p></body></html>"))


from mplwidget import MplWidget
import new_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
